version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    target-branch: "main"
    allow:
      - dependency-type: "all"
    labels:
      - "github_actions"
      - "main"
    reviewers:
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    target-branch: "main-v4"
    allow:
      - dependency-type: "all"
    labels:
      - "github_actions"
      - "main-v4"
    reviewers:
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella
