name: Docker Publish

on:
  push:
    branches:
      - snapshot
    # A tag will build and publish the Docker images
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ "snapshot" ]

jobs:
  build-and-push:
    strategy:
      matrix:
        dist: [corretto, debian, zulu, zulu-alpine, adoptopenjdk, msopenjdk]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo
        run: |
          echo "Build and publish Docker image: adaptris/interlok-base:${{ github.ref_name || 'snapshot' }}-${{ matrix.dist }}"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ./${{ matrix.dist }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: adaptris/interlok-base:${{ github.ref_name || 'snapshot' }}-${{ matrix.dist }}
          labels: interlok
          cache-from: type=gha
          cache-to: type=gha,mode=max
