name: Docker Publish

#on:
#  push:
#    branches: [ "snapshot" ]
    # Publish semver tags as releases.
#    tags: [ 'v*.*.*' ]
#  pull_request:
#    branches: [ "snapshot" ]

jobs:
  build-and-push:
    strategy:
      matrix:
        version: [10, 12, 14]
        dist: [corretto, debian, zulu, zulu-alpine, adoptopenjdk, msopenjdk]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@4
        with:
          context: ./${{ matrix.dist }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: adaptris/interlok-base:${{ matrix.dist }}snapshot
          labels: interlok
          cache-from: type=gha
          cache-to: type=gha,mode=max
