name: Docker

on:
  push:
    branches: snapshot
  schedule:
    - cron: '15 05 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Docker buildx
      run: |
        DOCKER_TARGETS=("eclipse-temurin" "liberica-alpine" "graalvm")
        DOCKER_IMAGE_SUFFIX=("" "-liberica-alpine" "-graalvm")
        DOCKER_IMAGE_PREFIX="lewinc/interlok-base"
        TARGET_PLATFORMS=("linux/amd64,linux/arm64,linux/arm/v7" "linux/amd64,linux/arm64" "linux/amd64,linux/arm64")
        for (( j=0; j<${#DOCKER_TARGETS[@]}; j++ ));
        do
          echo "-------- ${DOCKER_TARGETS[$j]}(${TARGET_PLATFORMS[$j]})"
          docker buildx build . --no-cache --platform ${TARGET_PLATFORMS[$j]} -t "$DOCKER_IMAGE_PREFIX:snapshot${DOCKER_IMAGE_SUFFIX[$j]}" -f "${DOCKER_TARGETS[$j]}/Dockerfile" --push
        done