name: Docker

on:
  push:
    branches: snapshot
  schedule:
    - cron: '15 05 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_target: [ 'eclipse-temurin::linux/amd64,linux/arm64,linux/arm/v7', 'liberica-alpine:-liberica-alpine:linux/amd64,linux/arm64' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Docker buildx ${{ matrix.docker_target }}
      run: |
        DOCKER_FILE=$(echo "${{ matrix.docker_target }}" | cut -f1 -d:)/Dockerfile
        DOCKER_IMAGE=lewinc/interlok-base:snapshot$(echo "${{ matrix.docker_target }}" | cut -f2 -d:)
        DOCKER_PLATFORM=$(echo "${{ matrix.docker_target }}" | cut -f3 -d:)
        echo "-------- Building ${DOCKER_IMAGE}(${DOCKER_PLATFORM}) using ${DOCKER_FILE}"
        docker buildx build . --no-cache --platform ${DOCKER_PLATFORM} -t "${DOCKER_IMAGE}" -f "${DOCKER_FILE}" --push
        echo "-------- Finished ${DOCKER_IMAGE}(${DOCKER_PLATFORM})"
