name: Docker

on:
  push:
    branches: snapshot
  schedule:
    - cron: '15 01 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
    - name: Docker buildx
      run: |
        docker buildx build . --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t lewinc/interlok-base:snapshot \
            -f eclipse-temurin/Dockerfile --push